# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f387e58944c7b535fd050d119aed0712dbc9de18307b61dcd062b50bc14ab02c1f78d0800b26ba10f4e016ee22a549719a91dc5537fde33419476e698bb912a

test:
  secret_key_base: 924d4aaa78a9cf52bc830b243d5e00d355b9a8d3f19773bd68d3f31974e43c0e6eafcfbc58f94ddf5dba1078acdbb2772eb96926b08807c18c754b481981d48c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
